SET pagesize 0;
SET arraysize 7;
SET linesize 1000;
SET serverout on;
EXECUTE dbms_output.enable(2000000);

DEFINE USER_ID = LIQUIBASE_PLAYGROUND;
DEFINE USER_PASSWORD = LIQUIBASE_PLAYGROUND;

BEGIN
	FOR i IN (SELECT USERNAME FROM ALL_USERS WHERE USERNAME = '&USER_ID') LOOP
		EXECUTE IMMEDIATE 'DROP USER &USER_ID CASCADE';
	END LOOP;
END;
/

CREATE USER "&USER_ID" IDENTIFIED BY &USER_PASSWORD ACCOUNT UNLOCK;
GRANT CONNECT, CREATE ANY CLUSTER, CREATE ANY JOB, CREATE ANY SEQUENCE, CREATE ANY SYNONYM, CREATE ANY TABLE, CREATE ANY TYPE, CREATE DATABASE LINK, CREATE SESSION, CREATE VIEW, DEBUG ANY PROCEDURE, DEBUG CONNECT SESSION, DROP ANY SYNONYM, RESOURCE, SELECT ANY DICTIONARY, UNLIMITED TABLESPACE, CREATE ANY PROCEDURE TO "&USER_ID";

EXIT;
